# Generated by Django 2.2.3 on 2019-09-18 21:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(default='09', max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='POSCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POS_category', models.CharField(max_length=50)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_Image', models.ImageField(blank=True, upload_to='IMAGES/POS/')),
                ('category_slug', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'POS category',
            },
        ),
        migrations.CreateModel(
            name='POSCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POS_brand', models.CharField(max_length=200)),
                ('POS_summary', models.CharField(max_length=200)),
                ('POS_Image', models.ImageField(blank=True, upload_to='IMAGES/POS/%Y/%m/%d')),
                ('POS_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='POS.POSCategory', verbose_name='POS category')),
            ],
            options={
                'verbose_name_plural': 'POS coll',
            },
        ),
        migrations.CreateModel(
            name='POSDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POS_Image', models.ImageField(blank=True, upload_to='IMAGES/POS/%Y/%m/%d')),
                ('POS_description', models.TextField(default='')),
                ('POS_price', models.CharField(default='توافقی', max_length=10)),
                ('POS_slug', models.CharField(default=1, max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('POS_brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='POS.POSCollection', verbose_name='POS brand')),
            ],
        ),
    ]
