# Generated by Django 2.2.3 on 2019-09-20 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_title', models.CharField(max_length=200)),
                ('essay_summary', models.CharField(max_length=200)),
                ('essay_Image', models.ImageField(blank=True, upload_to='IMAGES/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'essay',
            },
        ),
        migrations.CreateModel(
            name='EssayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_category', models.CharField(max_length=50)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_Image', models.ImageField(blank=True, upload_to='IMAGES/')),
                ('category_slug', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'essay category',
            },
        ),
        migrations.CreateModel(
            name='EssayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_sidebar', models.CharField(default='', max_length=200)),
                ('essay_demo', models.FileField(blank=True, upload_to='FILES/%Y/%m/%d')),
                ('essay_description', models.TextField(default='')),
                ('essay_price', models.CharField(default='1,500', max_length=10)),
                ('essay_slug', models.CharField(default=1, max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('essay_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='essay.Essay', verbose_name='essay')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نام', models.CharField(max_length=50)),
                ('نام_خانوادگی', models.CharField(max_length=50)),
                ('آدرس_ایمیل', models.EmailField(blank=True, max_length=254)),
                ('شماره_تماس', models.CharField(default='09', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EssayDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_size', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('essay_download', models.FileField(upload_to='DOWNLOADFILES/%Y/%m/%d')),
                ('essay_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='essay.EssayDetail', verbose_name='essay title')),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='essay_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='essay.EssayCategory', verbose_name='category'),
        ),
    ]
