# Generated by Django 3.0.6 on 2020-08-24 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نام', models.CharField(max_length=50)),
                ('نام_خانوادگی', models.CharField(max_length=50)),
                ('آدرس_ایمیل', models.EmailField(blank=True, max_length=254)),
                ('شماره_تماس', models.CharField(default='09', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_category', models.CharField(max_length=50)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_Image', models.ImageField(blank=True, upload_to='IMAGES/')),
                ('category_slug', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'video category',
            },
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='', max_length=50)),
                ('video_sidebar', models.CharField(default='', max_length=200)),
                ('video_demo', models.FileField(blank=True, upload_to='CLIPS/%Y/%m/%d')),
                ('video_description', models.TextField(default='')),
                ('video_size', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('video_price', models.CharField(default='5,000', max_length=10)),
                ('zarinpal_link', models.CharField(default='', max_length=200)),
                ('video_slug', models.CharField(default=1, max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_summary', models.CharField(max_length=200)),
                ('video_Image', models.ImageField(blank=True, upload_to='IMAGES/%Y/%m/%d')),
                ('video_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='video.VideoCategory', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_download', models.FileField(upload_to='DOWNLOADCLIPS/%Y/%m/%d')),
                ('video_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='video.VideoDetail', verbose_name='Video title')),
            ],
        ),
        migrations.AddField(
            model_name='videodetail',
            name='video_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='video.Videos', verbose_name='Videos'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نام', models.CharField(max_length=250)),
                ('دیدگاه', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to='video.VideoDetail', verbose_name='comments')),
            ],
        ),
    ]
