# Generated by Django 2.2.3 on 2019-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='video_sidebar',
            field=models.CharField(default='', max_length=200),
        ),
    ]
