# Generated by Django 2.2.3 on 2019-09-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videodetail_video_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_Image',
            field=models.ImageField(blank=True, upload_to='IMAGES/%Y/%m/%d'),
        ),
    ]
