# Generated by Django 2.2.3 on 2019-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190918_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نام', models.CharField(max_length=50)),
                ('نام_خانوادگی', models.CharField(max_length=50)),
                ('آدرس_ایمیل', models.EmailField(blank=True, max_length=254)),
                ('شماره_تماس', models.CharField(default='09', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
