# Generated by Django 2.2.3 on 2019-09-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='video_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='videodetail',
            name='video_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='video_price',
            field=models.CharField(default='5,000', max_length=10),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='video_download',
            field=models.FileField(upload_to='DOWNLOADCLIPS/%Y/%m/%d'),
        ),
    ]
