# Generated by Django 2.2.3 on 2019-11-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='zarinpal_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
