# Generated by Django 2.2.3 on 2019-09-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_num',
            field=models.CharField(default='09', max_length=15),
        ),
    ]
