# Generated by Django 2.2.3 on 2019-09-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
